### ISSUE TITLE
Missing linebreak

### ISSUE THREAD

**Issue by AnderssonPeter** [r3c/cottle#171]
Hi I have the following template
```
namespace {namespace};

public class {class}
\{
	public void Write()
	\{
		Console.WriteLine("{output}");
	\}
\}
```

and use the following code to render
```c#
var document = Document.CreateDefault(this.content).DocumentOrThrow;
return document.Render(Context.CreateBuiltin(new Dictionary<Value, Value>
{
    ["namespace"] = "Test",
    ["class"] = "Cottle",
    ["output"] = "Hello my lady"
}));
```

And get the following output:
```
namespace GraphQLTest;

public class Cottle{
	public void Write()
	{
		Console.WriteLine("Hello my lady");
	}
}
```

The { after Cottle should be on its own line?

**Comment by r3c** [comment]
Hello @AnderssonPeter! What you see here is a consequence of default text trimming strategy described [here](https://cottle.readthedocs.io/en/stable/page/04-configuration.html#trimfirstandlastblanklines). Because `{class}` is a code block its following line break is removed. You may counter this effect by either adding an extra blank line or switching to another text trimming strategy.

Unrelated to your question, but if you're generating C# code you may want to replace delimiters `{` and `}` by something else (e.g. `{{` and `}}`) so you don't need to escape every single brace in your code 🙂 (this is described [here](https://cottle.readthedocs.io/en/stable/page/04-configuration.html#delimiters-customization) FYI)
