### ISSUE TITLE
Add support for multi-line comments?

### ISSUE THREAD

**Issue by Tkael** [r3c/cottle#21]
Cottle currently seems to support only single line comments (http://r3c.github.io/cottle/#toc-2.8). Would it be possible to add support for multi-line comments? e.g.
```
{_ Starting my comment here
   {some code that I don't want to activate}
   {some code that I don't want to activate}
   {some code that I don't want to activate}
   {some code that I don't want to activate}
   {some code that I don't want to activate}
   {some code that I don't want to activate}
_}
```

 Thanks!

**Comment by r3c** [comment]
Hi, you can insert line breaks in your comments, only a closing "}" character will end it:

    { _ This is a
        multi-line
        comment }

I believe the issue you have is you're using comments to disable code, and this is unfortunately not supported (since a `}`) anywhere in the comment will close it). I can suggest two alternatives:

1 - Escape braces inside your comment so they don't end it too soon:

    { _ Starting comment here
        \{some text with escaped braces\}
        end of comment }

or:

2 - Disable code by adding impossible conditions that will be stripped away at parsing (so there will be no extract rendering cost):

    {if false:
        {some_code_you_want_to_disable}
    }

Please note in this second solution the code still needs to be syntactically valid as it will be seen as code by Cottle parser, but removed when the internal AST is built.
