### ISSUE TITLE
Unexpected rendered content

### ISSUE THREAD

**Issue by igitur** [r3c/cottle#73]
Hi,

Thanks, this library looks very promising. However, I must be missing something very basic.

I have this template:
```
{name}

{description}
```

And this code to render the content:
```c#
using (var template = new StreamReader(templatePath))
{
    var document = Document.CreateDefault(template).DocumentOrThrow;

    var context = Context.CreateBuiltin(new Dictionary<Value, Value>
    {
        ["name"] = "My name",
        ["description"] = "My description"
    });

    var content = document.Render(context);
}

```

The value of `content` is then: `My nameMy description`. The line-breaks just disappear.

I have read about the configuration settings, but the docs says that by default, plain-text rendering should give one character-level control. Did I miss something in the docs?

thanks

**Comment by r3c** [comment]
Hi @igitur, the section you're looking for in the documentation is [this one](https://cottle.readthedocs.io/en/stable/page/04-configuration.html#plain-text-trimming). Unless you change it in your configuration, you'll be using the default `DocumentConfiguration.TrimFirstAndLastBlankLines` trimming which is responsible for the result you have. You can switch to another option like `DocumentConfiguration.TrimNothing` if you don't want any character to be removed, or define your own if none from the builtin ones are good match for your needs. Hope that helps 🙂

**Comment by igitur** [comment]
Ah, thanks! Yes, that solves my problem.

But using `TrimNothing` then results in line breaks when I do something like:
```
{if len(items) > 0:
Some header
{for item in items:
{item}
}
}
```

Am I right? So I'll have to change that to 
```
{if len(items) > 0:Some header
{for item in items:{item}}
}
```

Or do you think it will be possible to write a custom trimmer to trim the linebreak if the line ends with a Cottle command?

**Comment by r3c** [comment]
This is more or less what the `DocumentConfiguration.TrimFirstAndLastBlankLines` was meant for, but it's not possible to tell whether a line break or some spaces are here for indenting code or if they should be preserved in the output. That's why this trimmer was designed to remove one blank line at the beginning and end of each text blocks, but this requires you to write _two_ line breaks if you want to preserve one. It's clearly not perfect and I'd gladly hear better suggestions if you have any 🙂 Some other template libraries use a special syntax to indicate when blank characters should be trimmed or not (e.g. Python's Jinja engine), but I feel this adds many odd characters in the template and I tried to avoid introducing something similar.

Let me know if you have any suggestion about this!
