### ISSUE TITLE
Pre Compiled Document

### ISSUE THREAD

**Issue by bsagal** [r3c/cottle#85]
Is there a way to store a Native Document for retrieval at a later time?

The template I am using will be available at compile time. I would like to compile it during the build and store it in the the dll (if necessary as an embedded resources).

**Comment by r3c** [comment]
Hi @bsagal, this is currently not available but would probably require a low amount of work. Before I can fully answer your question, would you mind telling me more about your use case? I assume you have a large number of templates and want to avoid paying the cost of compiling them at startup?

The code needed for saving a native document as an executable .dll library already exists, although I currently use it for testing purpose only and it's stripped out of production build. You can find it in file `src/Cottle/Documents/Emitted/Program.cs` starting at line 30 if you're interested. Something that could work would be to reuse a code similar to this one but allow saving multiple compiled templates inside a single .dll (as you probably don't want a .dll file per template). Such approach would require running the compiler when your solution is built so the .dll is generated and can be linked against your own application.

Another solution, if working with default documents instead of native ones could work for you, would be to implement some (de)serialization mechanism to save the compiled AST of a given document. Loading the AST would be significantly cheaper than parsing the original text, plus it would already have the optimization pass applied.

Please let me know more about what you're willing to achieve so I can advise on a solution 🙂
